In [2]:
import pandas
import numpy
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

***Define questions***

For our Project Part 2, we searched for the best predictors for state average SAT scores. However, say you were interested in increasing the average SAT score for a particular state. The predictors identified in Part 2 might be somewhat helpful, but it's likely that different states would have different predictors. We could redo what we did in Part 2 for each state, but that would be tedious. What if we could group states based on their educational data?

The US census bureau divides states into geographic regions for the purpose of data analysis (see: https://en.wikipedia.org/wiki/List_of_regions_of_the_United_States#Census_Bureau-designated_regions_and_divisions). It seems logical that we could do something similar, but based solely on educational data. Based on the data, we can use k-means clustering to figure out how to divide the states, and how many regions are best.

**Our Question is: How can states be divided into "regions" based on educational characteristics?**

***Collect Data***

We'll use our SAT data set from Part 2. We also found that the National Center for Educational Statistics (NCES) publishes a lot of demographic data for each school, including full time teacher employment, student race distribution, and free/reduced lunch eligibility. However, the NCES data is only available in CSV format from 2015 onward. Thus, we'll have to switch our year of analysis to the 2015-2016 school year, as opposed to the 2014-2015 school year for Part 2. (NCES website: https://nces.ed.gov/ccd/pubschuniv.asp)

***Process Data***

For the SAT data, we can use the same cleaning techniques as from Part 2, but for the 2015 data:

In [6]:
sat_data = pandas.read_csv("../data/school_scores.csv")

In [7]:
sat_data_2015 = sat_data.loc[sat_data["Year"] == 2015, :].iloc[:, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 19, 22, 
                                                                   25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61]].copy()
sat_data_2015["Total_Overall_Score"] = sat_data_2015["Total.Math"] + sat_data_2015["Total.Verbal"]
sat_data_2015 = sat_data_2015.drop(columns = ["Total.Math", "Total.Verbal"])
total_test_takers = sat_data_2015["Total.Test-takers"]
cols = ["Family Income.Between 20-40k.Test-takers", "Family Income.Between 40-60k.Test-takers", "Family Income.Between 60-80k.Test-takers", 
        "Family Income.Between 80-100k.Test-takers", "Family Income.Less than 20k.Test-takers", "Family Income.More than 100k.Test-takers",
        "GPA.A minus.Test-takers", "GPA.A plus.Test-takers", "GPA.A.Test-takers", "GPA.B.Test-takers", "GPA.C.Test-takers", 
        "GPA.D or lower.Test-takers", "GPA.No response.Test-takers", "Gender.Female.Test-takers", "Gender.Male.Test-takers"]
for col in cols:
    sat_data_2015[col] = sat_data_2015[col]/total_test_takers
sat_data_2015 = sat_data_2015.reset_index()
sat_data_2015.head()

,index,Year,State.Code,State.Name,Total.Test-takers,Academic Subjects.Arts/Music.Average GPA,Academic Subjects.Arts/Music.Average Years,Academic Subjects.English.Average GPA,Academic Subjects.English.Average Years,Academic Subjects.Foreign Languages.Average GPA,...,GPA.A minus.Test-takers,GPA.A plus.Test-takers,GPA.A.Test-takers,GPA.B.Test-takers,GPA.C.Test-takers,GPA.D or lower.Test-takers,GPA.No response.Test-takers,Gender.Female.Test-takers,Gender.Male.Test-takers,Total_Overall_Score
0,524,2015,AL,Alabama,2929,3.94,2.3,3.67,4.0,3.64,...,0.189143,0.182998,0.309662,0.264254,0.031410,0.000000,0.022533,0.572209,0.427791,1088
1,525,2015,AK,Alaska,3799,3.83,2.0,3.49,3.9,3.47,...,0.181627,0.073177,0.213740,0.359832,0.089234,0.003159,0.079231,0.569097,0.430903,1014
2,526,2015,AZ,Arizona,21545,3.87,2.3,3.52,3.9,3.51,...,0.204363,0.079322,0.237642,0.364632,0.063634,0.000743,0.049663,0.557624,0.442376,1052
3,527,2015,AR,Arkansas,1207,3.94,2.5,3.73,4.0,3.74,...,0.211268,0.196355,0.355427,0.195526,0.020713,0.000000,0.020713,0.566694,0.433306,1141
4,528,2015,CA,California,241553,3.79,1.9,3.42,3.9,3.42,...,0.189892,0.043046,0.176591,0.433416,0.087207,0.001221,0.068627,0.551502,0.448498,1003

We'll now switch to cleaning the NCES data. From the NCES page linked above, we grab 3 datasets for the 2015-2016 year: the ones for membership (for getting the race/ethnicity distribution), staff (for getting full-time staff employment), and lunch program eligibility (for getting free-reduced lunch program eligibility). We'll start with membership:

In [9]:
# Read in the data, all as strings due to the weird way the data is encoded
membership_unclean = pandas.read_csv("../data/Membership_1516.csv", dtype=str)
# Select only the State Code and total num of students of each race
membership_unclean = membership_unclean[["STABR", "AM", "AS", "HI", "BL", "WH", "HP", "TR"]]
# Get number columns back to ints
membership_unclean[["AM", "AS", "HI", "BL", "WH", "HP", "TR"]] = membership_unclean[["AM", "AS", "HI", "BL", "WH", "HP", "TR"]].astype(int)
# Replace any negatives with NaN
membership_clean = membership_unclean.replace(-1, numpy.nan).replace(-2, numpy.nan).replace(-9, numpy.nan)
for col in ["AM", "AS", "HI", "BL", "WH", "HP", "TR"]:
    # Replace any NaNs with the mean for the state
    membership_clean[col] = membership_clean[col].fillna(membership_clean.groupby("STABR")[col].transform("mean"))
    # If the state doesn't report in that racial category at all, impute with 0
    # Mainly because NY doesn't break out Hawaiian Native/Pacific Islander as a seperate group
    membership_clean[col] = membership_clean[col].fillna(0)
# Calculate total students per school 
membership_clean["TotalStudents"] = (membership_clean["AM"] + membership_clean["AS"] + membership_clean["HI"] + membership_clean["BL"] 
                                        + membership_clean["WH"] + membership_clean["HP"] + membership_clean["TR"])
# Calculate overall state totals, give columns clearer names
membership_totals = (membership_clean.groupby("STABR").sum()
                  .reset_index()).rename(columns={"STABR": "State.Code","AM": "AmericanIndianAlaskanNative", "AS": "Asian", "HI": "Hispanic",
                                                 "BL": "Black", "WH": "White", "HP": "HawaiianNativePacificIslander", 
                                                  "TR": "TwoOrMoreRaces"})
# Drop data for Bureau of Indian Affairs, Department of Defense, and Guam schools
membership_totals = (membership_totals.drop([4, 9, 13])).reset_index(drop = True)
# Convert to get relative racial/ethnic distribution for each state
for col in ["AmericanIndianAlaskanNative", "Asian", "Hispanic", "Black", "White", "HawaiianNativePacificIslander", "TwoOrMoreRaces"]:
    membership_totals[col] = membership_totals[col]/membership_totals["TotalStudents"]

In [10]:
membership_totals.head()

,State.Code,AmericanIndianAlaskanNative,Asian,Hispanic,Black,White,HawaiianNativePacificIslander,TwoOrMoreRaces,TotalStudents
0,AK,0.230583,0.059376,0.066578,0.031636,0.481457,0.027114,0.103256,1.324770e+05
1,AL,0.008835,0.014023,0.068233,0.332184,0.556319,0.000902,0.019504,8.216540e+05
2,AR,0.006360,0.015520,0.123193,0.207686,0.618289,0.006836,0.022116,4.921320e+05
3,AZ,0.045066,0.028018,0.449209,0.052778,0.394968,0.003265,0.026696,1.174507e+06
4,CA,0.005564,0.113766,0.540029,0.057806,0.240868,0.004891,0.037076,6.312578e+06

We then clean the data for free/reduced lunch eligibility. Since not all states break down the number of students who get free lunch vs the number who get only reduced price lunch (ie, they only report the total who get free OR reduced price lunch), we'll just look at the overall total. Overall, the cleaning will be similar to for the membership set:

In [12]:
# Read in the data, all as strings due to the weird way data is encoded
lunch_unclean = pandas.read_csv("../data/Lunch_1516.csv", dtype=str)
# Select only the State Code and total number of students eligible for free/reduced lunch
lunch_unclean = lunch_unclean[["STABR", "TOTFRL"]]
# Get numerical column back to an int type
lunch_unclean[["TOTFRL"]] = lunch_unclean[["TOTFRL"]].astype(int)
# Replace any negatives with NaN
lunch_unclean = lunch_unclean.replace(-1, numpy.nan).replace(-2, numpy.nan).replace(-9, numpy.nan)
# Replace NaN with state average
lunch_unclean["TOTFRL"] = lunch_unclean["TOTFRL"].fillna(lunch_unclean.groupby("STABR")["TOTFRL"].transform("mean"))
# Sum up each state
lunch_totals = (lunch_unclean.groupby("STABR").sum().reset_index()).rename(columns = {"STABR": "State.Code", "TOTFRL": "FreeReducedLunch"})
# Drop data for Bureau of Indian Affairs, Department of Defense, and Guam schools
lunch_totals = (lunch_totals.drop([4, 9, 13])).reset_index(drop = True)

In [13]:
lunch_totals.head()

  State.Code  FreeReducedLunch
0         AK      5.707440e+04
1         AL      4.204029e+05
2         AR      3.210340e+05
3         AZ      6.909038e+05
4         CA      3.755197e+06

Finally, we clean the data for full-time teacher employment. Note that this is NOT the exact number of full time teachers employed by the school. It is an estimate "computed by dividing the amount of time employed by the amount of time normally required for a full-time position." (quoted from https://nces.ed.gov/ccd/pdf/CCD_201516_File_Documentation_2017074.pdf). Nevertheless, it is still a useful metric, particularly for computing the state student to teacher ratio. We do the data cleaning much the same way as for the free/reduced lunch data:

In [15]:
# Read in the data, all as strings due to the weird way data is encoded
staff_unclean = pandas.read_csv("../data/Staff_1516.csv", dtype=str)
# Select only the State Code and equivalent number of full time educators
staff_unclean = staff_unclean[["STABR", "FTE"]]
# Get numerical column to a double type
staff_unclean[["FTE"]] = staff_unclean[["FTE"]].astype(float)
# Replace any negatives with NaN
staff_unclean = staff_unclean.replace(-1, numpy.nan).replace(-2, numpy.nan).replace(-9, numpy.nan)
# Sum up each state
staff_totals = (staff_unclean.groupby("STABR").sum().reset_index()).rename(columns = {"STABR": "State.Code", "FTE": "EquivFullTimeTeachers"})
# Drop data for American Samoa, Bureau of Indian Affairs, Department of Defense, and Guam schools
staff_totals = (staff_totals.drop([3, 5, 10, 14])).reset_index(drop = True)

In [16]:
staff_totals.head()

  State.Code  EquivFullTimeTeachers
0         AK                7777.88
1         AL               42161.58
2         AR               35803.87
3         AZ               47642.34
4         CA              262503.20

We can then merge all of the demographic data into one larger data frame:

In [18]:
# Merge Data
temp = pandas.merge(membership_totals, lunch_totals, how = "inner", on = "State.Code")
demographic_totals = pandas.merge(temp, staff_totals, how = "inner", on = "State.Code")

We then do a few final imputations. A few states didn't report the full time teacher employment, so that was imputated by the national average full-time teacher employment. Also, Massachusetts did not submit free or reduced-price lunch data, so the proportion was imputated from the national average, then applied to the total number of students in Massachusetts.

In [20]:
# Calculate Proportion of students getting free reduced lunch
demographic_totals["FreeReducedLunchProp"] = demographic_totals["FreeReducedLunch"]/demographic_totals["TotalStudents"]
# Massachusetts doesn't have free/reduced lunch data, so impute with national mean
demographic_totals["FreeReducedLunchProp"] = (demographic_totals["FreeReducedLunchProp"].replace(0, numpy.nan)
                                                .fillna(demographic_totals["FreeReducedLunchProp"].mean(skipna=True)))
# Some states don't equivalent full time educator data, so impute with national mean
demographic_totals["EquivFullTimeTeachers"] = (demographic_totals["EquivFullTimeTeachers"].replace(0, numpy.nan)
                                                .fillna(demographic_totals["EquivFullTimeTeachers"].mean(skipna=True)))
# Calculate Student Teacher ratio
demographic_totals["StudentTeacherRatio"] = demographic_totals["TotalStudents"]/demographic_totals["EquivFullTimeTeachers"]

In [21]:
# Manually calculate imputed number of students in MA eligible for free/reduced lunch from imputed proportion
# Might not end up needing, but fun to have 
demographic_totals.loc[19, "FreeReducedLunch"] = 0.512580 * 9.534230e+05

We then merge the SAT and demographic data sets into a larger, combined data set:

In [29]:
full_combined_data_2015 = pandas.merge(sat_data_2015, demographic_totals, how = "inner", on = "State.Code").drop(columns = ["index"])
full_combined_data_2015.head()

,Year,State.Code,State.Name,Total.Test-takers,Academic Subjects.Arts/Music.Average GPA,Academic Subjects.Arts/Music.Average Years,Academic Subjects.English.Average GPA,Academic Subjects.English.Average Years,Academic Subjects.Foreign Languages.Average GPA,Academic Subjects.Foreign Languages.Average Years,...,Hispanic,Black,White,HawaiianNativePacificIslander,TwoOrMoreRaces,TotalStudents,FreeReducedLunch,EquivFullTimeTeachers,FreeReducedLunchProp,StudentTeacherRatio
0,2015,AL,Alabama,2929,3.94,2.3,3.67,4.0,3.64,2.5,...,0.068233,0.332184,0.556319,0.000902,0.019504,8.216540e+05,4.204029e+05,42161.58,0.511654,19.488216
1,2015,AK,Alaska,3799,3.83,2.0,3.49,3.9,3.47,2.2,...,0.066578,0.031636,0.481457,0.027114,0.103256,1.324770e+05,5.707440e+04,7777.88,0.430825,17.032533
2,2015,AZ,Arizona,21545,3.87,2.3,3.52,3.9,3.51,2.5,...,0.449209,0.052778,0.394968,0.003265,0.026696,1.174507e+06,6.909038e+05,47642.34,0.588250,24.652589
3,2015,AR,Arkansas,1207,3.94,2.5,3.73,4.0,3.74,2.6,...,0.123193,0.207686,0.618289,0.006836,0.022116,4.921320e+05,3.210340e+05,35803.87,0.652333,13.745218
4,2015,CA,California,241553,3.79,1.9,3.42,3.9,3.42,2.8,...,0.540029,0.057806,0.240868,0.004891,0.037076,6.312578e+06,3.755197e+06,262503.20,0.594875,24.047623

In [33]:
# Data without any non-normalized variables
trimmed_combined_data_2015 = full_combined_data_2015.drop(columns = ["Total.Test-takers", "TotalStudents", "FreeReducedLunch", "EquivFullTimeTeachers"])
# Only predictors from Part 2 - used for new linear model
only_predictors_data_2015 = full_combined_data_2015[["Total_Overall_Score", "Academic Subjects.Arts/Music.Average GPA", 
                                                     "Academic Subjects.English.Average GPA", 
                                                     "Academic Subjects.Foreign Languages.Average GPA", 
                                                     "Academic Subjects.Mathematics.Average GPA", 
                                                     "Academic Subjects.Natural Sciences.Average GPA",
                                                     "Academic Subjects.Social Sciences/History.Average GPA",
                                                     "Academic Subjects.Arts/Music.Average Years",  
                                                     "Academic Subjects.English.Average Years",
                                                     "Academic Subjects.Mathematics.Average Years",
                                                     "Academic Subjects.Natural Sciences.Average Years",
                                                     "Family Income.Less than 20k.Test-takers", "Family Income.Between 20-40k.Test-takers",
                                                     "Family Income.Between 60-80k.Test-takers", "Family Income.Between 80-100k.Test-takers",
                                                     "Family Income.More than 100k.Test-takers", 'GPA.D or lower.Test-takers',
                                                     'GPA.A plus.Test-takers', 'GPA.No response.Test-takers', 'GPA.A.Test-takers',
                                                     'GPA.A minus.Test-takers']]
predictors_new_vars = full_combined_data_2015[["Total_Overall_Score", "Academic Subjects.Arts/Music.Average GPA",
                                               "Academic Subjects.English.Average GPA", "Academic Subjects.Foreign Languages.Average GPA",
                                               "Academic Subjects.Mathematics.Average GPA", "Academic Subjects.Natural Sciences.Average GPA",
                                               "Academic Subjects.Social Sciences/History.Average GPA", 
                                               "Academic Subjects.Arts/Music.Average Years", "Academic Subjects.English.Average Years", 
                                               "Academic Subjects.Mathematics.Average Years", 
                                               "Academic Subjects.Natural Sciences.Average Years", "Family Income.Less than 20k.Test-takers",
                                               "Family Income.Between 20-40k.Test-takers", "Family Income.Between 60-80k.Test-takers", 
                                               "Family Income.Between 80-100k.Test-takers", "Family Income.More than 100k.Test-takers",
                                               'GPA.D or lower.Test-takers', 'GPA.A plus.Test-takers', 'GPA.No response.Test-takers',
                                               'GPA.A.Test-takers', 'GPA.A minus.Test-takers', "AmericanIndianAlaskanNative", "Asian",
                                               "Hispanic", "Black", "White", "HawaiianNativePacificIslander", "TwoOrMoreRaces", 
                                               "FreeReducedLunchProp", "StudentTeacherRatio"]]

**Comments and Challenges on Data Cleaning**

The data from the NCES contained data for more places then the SAT data. Namely, it contained data for schools in American Samoa (free/reduced lunch eligibity only), schools operated by the Bureau of Indian Affairs, schools operated by the Department of Defense, and schools in Guam. This data was dropped simply because there was no match in the SAT data set. It's also possible that the sets of schools in each NCES file weren't the same (ie, not all schools had data in all files). However, there is likely a large enough amount of schools for each state that the subtraction of a few wouldn't have a huge effect on the data. Finally, the NCES data only covers public schools, while the SAT data covers all students who took the SAT in the state, including students who don't go to public school. However, it is likely that the number of such students is small enough that it wouldn't meaningfully affect the demographics.